### ISSUE TITLE
Type mobile has black background and type tab has white background

### ISSUE THREAD

**Issue by codingyourlife** [TheoOkafor/react-device-emulator#15]
Somehow type mobile changes my background color to black. Not sure why this is. How can I change it to white?

**Comment by TheoOkafor** [comment]
Hi @codingyourlife,

Can you provide more details, please?
Screenshots and context will be very helpful.

**Comment by codingyourlife** [comment]
Hi! Sorry I stopped using the plugin then.
If it helps the Phone variant was always with a black screen or black background as if the device was turned off. I remember that when I just replaced the variant to Tablet that the screen had a white background. Should be easy to reproduce. If not just close...

**Comment by vasilevich** [comment]
same issue here, makes no sense,  you can see it even iin your own demo GIF:
https://user-images.githubusercontent.com/31534129/65742850-3d7fbd80-e0f2-11e9-8a68-5783a1c3dad7.gif

code:
```
 <DeviceEmulator type="mobile">
                  <h1>Welcome to React Device Emulator</h1>
                </DeviceEmulator>
```

Thanks for working on this module!
