### ISSUE TITLE
Package for types

### ISSUE THREAD

**Issue by codingyourlife** [TheoOkafor/react-device-emulator#16]
react-device-emulator does not seem to have a package at npm install @types/react-device-emulator

**Comment by TheoOkafor** [comment]
Hi @codingyourlife,

Thank you for reaching out. Can you provide more details about this issue?

**Comment by codingyourlife** [comment]
It is not typescript typesafe. Many packages offer an @types/package-name package to have typing suggestions in VSCode or other editors.
