### ISSUE TITLE
How can I disable options?

### ISSUE THREAD

**Issue by denaldhushi** [TheoOkafor/react-device-emulator#45]
hi,
How can I disable these 3 options and change the size of the device ?
![1](https://user-images.githubusercontent.com/20266205/228954773-67ce9544-2d83-4d23-b765-3fe14510d293.png)

**Comment by TheoOkafor** [comment]
The buttons are provided by default. Here's how to disable them:
```
<DeviceEmulator
    withDeviceSwitch={false}
    withRotator={false}
>
    <div>Welcome to React Device Emulator</div>
 </DeviceEmulator>
 ```

**Comment by denaldhushi** [comment]
Thanks!
Do u have any option to change the size of the device ? Because it looks a bit big.
![1](https://user-images.githubusercontent.com/20266205/229211028-514d60ad-2c12-43c1-9ad3-0e2b285645de.png)

**Comment by TheoOkafor** [comment]
@denaldhushi There's no built-in way of doing this currently, but the CSS that makes this work is easy to hack.
You can select the classes and resize them in your CSS file. In your case, the CSS classes of interest are `.mobile-chrome` and `.mobile-frame`. The current style is found [here](https://github.com/TheoOkafor/react-device-emulator/blob/master/src/styles/style.css)

**Comment by denaldhushi** [comment]
Thank you!!
